device: cpu

# BEGIN Local development

defaults:
  - model: bert-base-uncased
  - dataset: openwebtext
  - _self_

dataset:
  take: 100
sequence_length: 40

# END Local development

sequence_length_step_size: 100  # For experiment sweep

hydra:
  job_logging:
    formatters:
      simple:
        format: '%(message)s'
  sweeper:
    params:
      model: glob(*)
      dataset: glob(*)
      sequence_length: range(0,${model.max_sequence_length},step=${sequence_length_step_size})
      dataset.take: 10  # Note, should be 10000
